2020-12-19 22:31:54,372-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-19 22:31:59,312-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额小数超过两位 != 金额小数超过两位
2020-12-19 22:32:00,934-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-19 22:32:02,757-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-19 22:32:04,390-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额为空 != 金额为空
2020-12-19 22:32:05,781-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 会员id为空 != 用户id为空
2020-12-19 22:32:07,048-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 2 != 1007
2020-12-19 22:41:09,336-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: OK != 数值参数格式不正确
2020-12-19 22:41:09,754-test_004_withdraw_method1.py-109-api_test_v2-ERROR-日志信息:测试用例失败： :: OK != 数值参数格式不正确
2020-12-19 22:41:17,775-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额为空 != 金额为空
2020-12-19 22:41:18,223-test_004_withdraw_method1.py-109-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额为空 != 金额为空
2020-12-19 22:41:20,695-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 2 != 1007
2020-12-19 22:41:21,115-test_004_withdraw_method1.py-109-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 1007
2020-12-19 22:41:22,945-test_004_withdraw_method1.py-109-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('0.01') != Decimal('0.01000000000000000020816681711721685132943093776702880859375')
2020-12-19 22:45:44,458-test_004_withdraw_method1.py-84-api_test_v2-ERROR-日志信息:用例测试失败： :: 会员不存在 != 无权限访问，请检查参数
2020-12-19 22:45:44,926-test_004_withdraw_method1.py-109-api_test_v2-ERROR-日志信息:测试用例失败： :: 会员不存在 != 无权限访问，请检查参数
2020-12-19 22:45:46,859-test_004_withdraw_method1.py-109-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('0.01') != Decimal('0.01000000000000000020816681711721685132943093776702880859375')
2020-12-19 23:06:59,449-test_005_withdraw_method2.py-100-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-19 23:07:02,294-test_005_withdraw_method2.py-100-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-19 23:07:08,039-test_005_withdraw_method2.py-100-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-19 23:13:44,511-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('100.10') != Decimal('100.099999999999994315658113919198513031005859375')
2020-12-19 23:13:46,636-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('100.22') != Decimal('100.219999999999998863131622783839702606201171875')
2020-12-19 23:13:55,376-test_005_withdraw_method2.py-100-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-19 23:13:55,810-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-19 23:16:48,334-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('100.90') != Decimal('100.900000000000005684341886080801486968994140625')
2020-12-19 23:16:50,441-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('100.11') != Decimal('100.1099999999999994315658113919198513031005859375')
2020-12-19 23:16:57,781-test_005_withdraw_method2.py-100-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-19 23:16:58,239-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-19 23:19:26,799-test_005_withdraw_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('100.11') != 100.11
2020-12-19 23:53:00,809-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-19 23:53:01,616-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-19 23:53:24,760-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-19 23:53:26,142-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-19 23:53:58,211-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-19 23:54:09,848-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-19 23:54:10,933-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:00:30,727-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:00:32,031-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:01:40,278-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:01:52,059-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:01:53,437-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:02:17,742-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:02:20,312-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:02:36,338-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:02:47,583-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:02:48,778-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:02:50,024-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:03:12,978-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:04:28,336-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:05:15,732-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:05:26,145-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:06:37,299-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:06:50,897-test_001_register.py-74-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:12:31,841-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:12:32,248-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:12:39,965-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:12:40,363-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:12:43,905-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额小数超过两位 != 金额小数超过两位
2020-12-20 00:12:44,361-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额小数超过两位 != 金额小数超过两位
2020-12-20 00:12:45,812-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:12:46,267-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:12:47,586-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:12:48,094-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:12:49,502-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额为空 != 金额为空
2020-12-20 00:12:49,932-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额为空 != 金额为空
2020-12-20 00:12:51,486-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 会员id为空 != 用户id为空
2020-12-20 00:12:51,912-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 会员id为空 != 用户id为空
2020-12-20 00:12:53,052-test_004_withdraw_method1.py-85-api_test_v2-ERROR-日志信息:用例测试失败： :: 2 != 1007
2020-12-20 00:12:53,459-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 1007
2020-12-20 00:12:55,399-test_004_withdraw_method1.py-110-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('0.01') != Decimal('0.01000000000000000020816681711721685132943093776702880859375')
2020-12-20 00:28:09,213-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('100.10') != 100.1
2020-12-20 00:28:10,433-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 2 != 0
2020-12-20 00:28:10,957-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-20 00:28:17,774-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:28:18,401-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:28:21,239-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:28:21,698-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:28:26,977-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:28:27,438-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:31:48,905-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('1000.11') != 1000.11
2020-12-20 00:31:55,244-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:31:55,700-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:31:58,762-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:31:59,209-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:32:01,019-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:32:01,480-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 余额必须大于0并且小于或者等于5000000 != 余额必须大于0并且小于或者等于500000
2020-12-20 00:34:58,013-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('1000.11') != 1000.11
2020-12-20 00:35:05,696-test_005_withdraw_method2.py-98-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-20 00:35:06,475-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-20 00:37:11,247-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('1000.11') != Decimal('1000.1100000000000136424205265939235687255859375')
2020-12-20 00:38:53,361-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('1000.19') != Decimal('1000.19000000000005456968210637569427490234375')
2020-12-20 00:40:06,436-test_005_withdraw_method2.py-124-api_test_v2-ERROR-日志信息:测试用例失败： :: Decimal('1770738.149999999999945430318') != Decimal('1770738.15')
2020-12-20 19:45:20,604-test_006_add_loan_method1.py-78-api_test_v2-ERROR-日志信息:用例测试失败： :: 借款期限为空 != 借款期限为
2020-12-20 19:45:21,197-test_006_add_loan_method1.py-100-api_test_v2-ERROR-日志信息:测试用例失败： :: 借款期限为空 != 借款期限为
2020-12-20 19:46:15,383-test_006_add_loan_method1.py-78-api_test_v2-ERROR-日志信息:用例测试失败： :: 借款期限为空 != 借款期限为
2020-12-20 19:46:15,993-test_006_add_loan_method1.py-100-api_test_v2-ERROR-日志信息:测试用例失败： :: 借款期限为空 != 借款期限为
2020-12-20 19:46:17,977-test_006_add_loan_method1.py-78-api_test_v2-ERROR-日志信息:用例测试失败： :: 借款期限单位为天的项目,期限范围为10到45天(包含10天和45天) != 借款期限单位为月的项目,期限范围为1到36个月(包含1个月和36个月)
2020-12-20 19:46:18,597-test_006_add_loan_method1.py-100-api_test_v2-ERROR-日志信息:测试用例失败： :: 借款期限单位为天的项目,期限范围为10到45天(包含10天和45天) != 借款期限单位为月的项目,期限范围为1到36个月(包含1个月和36个月)
2020-12-20 19:46:20,208-test_006_add_loan_method1.py-78-api_test_v2-ERROR-日志信息:用例测试失败： :: 借款期限单位为天的项目,期限范围为10到45天(包含10天和45天) != 借款期限单位为月的项目,期限范围为1到36个月(包含1个月和36个月)
2020-12-20 19:46:20,801-test_006_add_loan_method1.py-100-api_test_v2-ERROR-日志信息:测试用例失败： :: 借款期限单位为天的项目,期限范围为10到45天(包含10天和45天) != 借款期限单位为月的项目,期限范围为1到36个月(包含1个月和36个月)
2020-12-20 19:46:22,453-test_006_add_loan_method1.py-78-api_test_v2-ERROR-日志信息:用例测试失败： :: 借款期限单位为天的项目,期限范围为10到45天(包含10天和45天) != 借款期限单位为月的项目,期限范围为1到36个月(包含1个月和36个月)
2020-12-20 19:46:23,021-test_006_add_loan_method1.py-100-api_test_v2-ERROR-日志信息:测试用例失败： :: 借款期限单位为天的项目,期限范围为10到45天(包含10天和45天) != 借款期限单位为月的项目,期限范围为1到36个月(包含1个月和36个月)
2020-12-20 20:01:41,548-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:01:43,881-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:05:47,336-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:05:49,690-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:05:52,021-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:05:54,515-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:05:56,872-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:05:59,118-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:06:01,556-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:06:03,655-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-20 20:06:05,847-test_006_add_loan_method1.py-104-api_test_v2-ERROR-日志信息:测试用例失败：None is not true
2020-12-23 00:51:24,801-test_007_audit_loan.py-109-api_test_v2-ERROR-日志信息:用例测试失败： :: 非法的项目id != 项目不在审核中状态
2020-12-23 00:51:25,331-test_007_audit_loan.py-133-api_test_v2-ERROR-日志信息:测试用例失败： :: 非法的项目id != 项目不在审核中状态
2020-12-26 16:58:21,516-test_002_login.py-49-api_test_v2-ERROR-日志信息:测试用例失败： :: 1001 != 0
2020-12-27 17:11:49,601-test_009_update_nickname_method2.py-101-api_test_v2-ERROR-日志信息:用例测试失败： :: 2 != 0
2020-12-27 17:11:50,169-test_009_update_nickname_method2.py-126-api_test_v2-ERROR-日志信息:测试用例失败： :: 2 != 0
2020-12-27 23:49:07,126-test_010_info_method2.py-94-api_test_v2-ERROR-日志信息:用例测试失败： :: 1004 != 0
2020-12-27 23:49:07,697-test_010_info_method2.py-117-api_test_v2-ERROR-日志信息:测试用例失败： :: 1004 != 0
2020-12-27 23:49:14,155-test_010_info_method2.py-94-api_test_v2-ERROR-日志信息:用例测试失败： :: 1005 != 2
2020-12-27 23:49:14,769-test_010_info_method2.py-117-api_test_v2-ERROR-日志信息:测试用例失败： :: 1005 != 2
2020-12-27 23:51:39,074-test_010_info_method2.py-94-api_test_v2-ERROR-日志信息:用例测试失败： :: 1004 != 0
2020-12-27 23:51:39,642-test_010_info_method2.py-117-api_test_v2-ERROR-日志信息:测试用例失败： :: 1004 != 0
2020-12-27 23:51:45,894-test_010_info_method2.py-94-api_test_v2-ERROR-日志信息:用例测试失败： :: 1005 != 2
2020-12-27 23:51:46,475-test_010_info_method2.py-117-api_test_v2-ERROR-日志信息:测试用例失败： :: 1005 != 2
2020-12-27 23:54:52,593-test_010_info_method2.py-95-api_test_v2-ERROR-日志信息:用例测试失败： :: 1004 != 0
2020-12-27 23:54:53,323-test_010_info_method2.py-118-api_test_v2-ERROR-日志信息:测试用例失败： :: 1004 != 0
2020-12-27 23:55:00,625-test_010_info_method2.py-95-api_test_v2-ERROR-日志信息:用例测试失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-27 23:55:01,246-test_010_info_method2.py-118-api_test_v2-ERROR-日志信息:测试用例失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-27 23:55:45,331-test_010_info_method2.py-95-api_test_v2-ERROR-日志信息:用例测试失败： :: 1004 != 0
2020-12-27 23:55:45,919-test_010_info_method2.py-118-api_test_v2-ERROR-日志信息:测试用例失败： :: 1004 != 0
2020-12-27 23:55:52,680-test_010_info_method2.py-95-api_test_v2-ERROR-日志信息:用例测试失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-27 23:55:53,245-test_010_info_method2.py-118-api_test_v2-ERROR-日志信息:测试用例失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:06:32,610-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 1007
2020-12-28 00:06:33,192-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 1007
2020-12-28 00:06:34,169-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-28 00:06:34,838-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-28 00:06:35,765-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 1005
2020-12-28 00:06:36,370-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 1005
2020-12-28 00:07:50,555-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 1007
2020-12-28 00:07:51,166-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 1007
2020-12-28 00:07:52,074-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 2
2020-12-28 00:07:52,681-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 2
2020-12-28 00:07:53,544-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: 0 != 1005
2020-12-28 00:07:54,154-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: 0 != 1005
2020-12-28 00:09:57,369-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:09:57,960-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:13:08,072-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:13:08,818-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:14:55,237-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:14:55,842-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: ""a1770256550"" != 会员不存在
2020-12-28 00:15:41,691-test_010_info_method2.py-96-api_test_v2-ERROR-日志信息:用例测试失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "a1770256550" != 会员不存在
2020-12-28 00:15:42,250-test_010_info_method2.py-119-api_test_v2-ERROR-日志信息:测试用例失败： :: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Long'; nested exception is java.lang.NumberFormatException: For input string: "a1770256550" != 会员不存在
